version: '3.4'
services:
  proxy:
    image: lucj/kernelci-proxy:${TAG:-latest}
    ports:
      - 8083:8080
      - 8084:8081
      - 8085:8082
    volumes:
      - storage:/usr/share/nginx/html/kernelci/logs
    deploy:
      restart_policy:
        condition: on-failure
  frontend:
    image: lucj/kernelci-frontend:${TAG:-latest}
    deploy:
      restart_policy:
        condition: on-failure
  backend:
    image: lucj/kernelci-backend:${TAG:-latest}
    volumes:
      - storage:/var/www/images/kernel-ci
    deploy:
      restart_policy:
        condition: on-failure
  celery:
    image: lucj/kernelci-celery:${TAG:-latest}
    volumes:
      - storage:/var/www/images/kernel-ci
    deploy:
      restart_policy:
        condition: on-failure
  redis:
    image: redis:3.2
    deploy:
      restart_policy:
        condition: on-failure
  mongo:
    image: mongo:3.4
    volumes:
      - database:/data/db
    deploy:
      restart_policy:
        condition: on-failure
volumes:
  database:
  storage:
